### ISSUE TITLE
Display all image thumbnails

### ISSUE THREAD

**Issue by yglodt** [FLamparski/fw-mediaviewer#6]
Hi,

first let me say that fw-mediaviewer is the best gallery element I have seen so far for Polymer.

Is it possible to have it display all the items in an overview page using the thumbnail-url as image source?

Clicking/tapping on a thumbnail should then open the image in full size.

**Comment by FLamparski** [comment]
Hi, thanks! However this is not a "gallery" component per se, it's just a media album viewer.

If you want to display a list of thumbnails which take you to the viewer when pressed, you can use iron-list in grid mode, feeding it the same list as to fw-mediaviewer. That way the index of the thumbnail will match the index of the media in the list. You can then open the media viewer on a specific item by setting the index (first demo on the fw-mediaviewer demo page).

https://elements.polymer-project.org/bower_components/iron-list/demo/grid.html

**Comment by yglodt** [comment]
Hi Filip,

thanks for your input and your suggestion. I'll go that way.

KR,
Yves
